# Generated by Django 3.2.5 on 2025-03-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_department_hiredemployee_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredemployee',
            name='datetime',
            field=models.CharField(max_length=100),
        ),
    ]
